### PR TITLE
changed all tests to match the object array

### PR DESCRIPTION
**Pull request by Danijj89**
I changed the tests for all the other arrays to match the one from objects. I tested it with valgrind and there are no memory leaks. Consider merging this. Thanks!

### CODE REVIEW

**Comment by rohitppathak** [comment]
Is there any way you can change the tests to have the user handle all the memory management? I believe I might have been mistaken yesterday. We can't test equal on Objects if the array returns a copy. And for the behavior being unsafe, I believe it's okay, as if the user deletes a String and tries to access that same element from the array, they should get an error since they have already deleted the String.

**Comment by Danijj89** [comment]
I solved the issue of cloning object by not allowing it in the first place since creating an array with Objects doesn’t really make sense if you think about it. Object exists so that all classes can inherit from it. All the tests rely on strings so no object cloning is required. You just have to declare it in the superclass (maybe throwing an error if anyone tries to use it) and then override it in the child classes. The problem of allowing users to manage it is that it is really hard to manage and remember what is already freed and what is not, and leads to hard to debug segfaults. Having the invariant that the array always owns its values is something nice that you can rely on

**Comment by rohitppathak** [comment]
I understand that it doesn't really make sense, but from the assignment it states:
`For Array, your design should accommodate at least Arrays of Object and String.`
In addition, the Queue and Map both explicitly should support Objects as well. Returning a copy for Arrays would mean the same thing should be the case for Maps and Queues as well, but our implementations and specs from other groups for those don't support that.

**Comment by Danijj89** [comment]
All my other implementations and specs teams are following this other ownership model though, so i think we would either need more clarification from the specs provider or we can each write our own tests

**Comment by alexey-petrusevich** [comment]
As far as I understand, there is a disagreement between the test file. I've provided the implementation of arrays to the best of my knowledge to satisfy the needs of this assignment. Specifically after revealing that the excessive code duplication is what is expected from this assignment. I'll be glad to merge as long as both of you can agree on the contents of the tests.

**Comment by rohitppathak** [comment]
I don't think both of our groups can use this test file, since we're doing different memory management methods. The original test file assumed that the user has responsibility for the objects, which is what we implemented. We'd really appreciate if the test stays the same, or else our implementation won't pass at all (bad access memory error).

**Comment by alexey-petrusevich** [comment]
I'm sorry, but there has to be some sort of conclusion on implementation. At least that is what I was told by the instructor.

**Comment by rohitppathak** [comment]
I believe you as the API spec designer need to decide which implementation to choose, as you are responsible for the test file. Your original test file had the Array not return copies and had the user delete the original elements, which is what we implemented.

**Comment by alexey-petrusevich** [comment]
I'll leave the interface at its current state since it works for at least one of you. You can rewrite the tests so your implementation passes it all and include that in your documentation accompanying this assignment.

**Comment by Danijj89** [comment]
I think the current tests won't work for either for us. In order to make it work at least for one of us you would have to either revert the previous merge or merge this PR to master

**Comment by rohitppathak** [comment]
The current tests work for us.

**Comment by alexey-petrusevich** [comment]
OK great. I'm sorry it didn't work for one of the teams. You may change the test file per your implementation. I wish I could do something else, but I cannot be jumping back and forth.

**Pull request closed without merging**
