### PR TITLE
Fixed test

### PR DESCRIPTION
**Pull request by rohitppathak**
There were errors in the test file which my partner and I found, both compilation and logical (we believe). Could the owner and the other groups go through our pull request and see if our changes for the file make sense? This would make it much easier for us and the other implementation groups so we can avoid changing code at the last minute.

https://github.com/alexey-petrusevich/CS_4500_A1_part2/pull/18/files?w=1

^ this link will let you compare the file ignoring whitespace diff

### CODE REVIEW

**Comment by Danijj89** [comment]
Correct me if I'm wrong, but if the array gets ownership of the objects that are inserted into the array, then those objects should be deleted in the destructor of the array and not outside of it, which would cause a double delete error.

**Comment by rohitppathak** [comment]
I believe the user will have the responsibility of deleting them, not the array, since the user is the one that made the Strings and Objects in the first place

**Comment by Danijj89** [comment]
Does this mean that we would have to make a copy of each object we add into the array? If so, we would need a clone method or a constructor for making a copy for both the string and the object class

**Comment by Danijj89** [comment]
I’m fine going with this approach if this is how it was intended to work

**Comment by rohitppathak** [comment]
Our implementation didn't make a copy of anything. We just added the object inside of the array as is.

**Comment by Danijj89** [comment]
From my understanding, this doesn’t seem safe. I believe that the array should either claim ownership, in which case it has the responsibility to free it, or it should make a copy of it so that if the original object is deleted, it will not affect the one inside the array. Else if we store the pointer to the original object and somebody deletes it, we would have memory issues since we still have a pointer to that address. Please correct me if I’m wrong.

**Comment by rohitppathak** [comment]
I believe you're right. I think the array should make a copy of the object, so the user has to delete the original object and the array has to delete the copy.

**Comment by Danijj89** [comment]
This would make sense. If the specs could be updated to reflect this, we could make a test suite that matches everyone’s implementation

**Comment by rohitppathak** [comment]
I think this test suite should still be unaffected though right? The user still has to delete every object they create.

**Comment by Danijj89** [comment]
Yes it would be unaffected. However it would be nice if we could also change the tests for set such that it only allows setting values for indexes between 0 and length off array (excluded), since setting at random indexes would introduce the possibility of nullptrs everywhere. It would be nice if we could make it behave more similar to an arraylist

**Comment by alexey-petrusevich** [comment]
I'm approving this pull requests. If you find any other suggestions about the code or problems with tests, it would be much easier of you create pull request instead of filiing a new issue unless it is for clarification. Thanks.

**Comment by alexey-petrusevich** [comment]
Merged.

**Pull request merged**
